use std::env;
use std::fs::File;
use std::io::{self, Write};

fn main() {
    let args: Vec<String> = env::args().collect();

    if args.len() != 2 {
        eprintln!("Usage: generate_ast <output directory>");
        std::process::exit(64);
    }

    let output_dir = &args[1];

    // Expr 타입 정의
    if let Err(e) = define_ast(
        output_dir,
        "Expr",
        &[
            "Binary   : Box<Expr> left, Token operator, Box<Expr> right",
            "Grouping : Box<Expr> expression",
            "Literal  : LiteralValue value",
            "Unary    : Token operator, Box<Expr> right",
        ],
    ) {
        eprintln!("Error generating Expr: {}", e);
        std::process::exit(1);
    }

    println!("Successfully generated AST files in '{}'", output_dir);
}

fn define_ast(output_dir: &str, base_name: &str, types: &[&str]) -> io::Result<()> {
    let path = format!("{}/{}.rs", output_dir, base_name.to_lowercase());
    let mut file = File::create(&path)?;

    // 파일 헤더 및 imports
    writeln!(file, "// Auto-generated by tools/generate_ast.rs")?;
    writeln!(file, "// Do not edit manually\n")?;
    writeln!(file, "use crate::token::Token;\n")?;

    // LiteralValue enum 정의 (Option 대신 명시적 타입 사용)
    writeln!(file, "#[derive(Debug, Clone, PartialEq)]")?;
    writeln!(file, "pub enum LiteralValue {{")?;
    writeln!(file, "    Number(f64),")?;
    writeln!(file, "    String(String),")?;
    writeln!(file, "    Boolean(bool),")?;
    writeln!(file, "    Nil,")?;
    writeln!(file, "}}\n")?;

    // Base Enum 생성
    write_base_enum(&mut file, base_name, types)?;

    // 각 타입별 Struct 생성
    for type_def in types {
        write_type(&mut file, type_def)?;
    }

    println!("Generated: {}", path);
    Ok(())
}

fn write_base_enum(file: &mut File, base_name: &str, types: &[&str]) -> io::Result<()> {
    writeln!(file, "#[derive(Debug, Clone, PartialEq)]")?;
    writeln!(file, "pub enum {} {{", base_name)?;

    for type_def in types {
        let class_name = type_def.split(':').next().unwrap().trim();
        writeln!(file, "    {}({}),", class_name, class_name)?;
    }

    writeln!(file, "}}\n")?;
    Ok(())
}

fn write_type(file: &mut File, type_def: &str) -> io::Result<()> {
    // "Binary : Box<Expr> left, Token operator, Box<Expr> right" 파싱
    let mut parts = type_def.split(':');
    let class_name = parts.next().unwrap().trim();
    let fields = parts.next().unwrap_or("").trim();

    // Struct 정의
    writeln!(file, "#[derive(Debug, Clone, PartialEq)]")?;
    writeln!(file, "pub struct {} {{", class_name)?;

    // 필드 작성
    if !fields.is_empty() {
        for field in fields.split(',') {
            let field = field.trim();
            if !field.is_empty() {
                // "Box<Expr> left" -> "left: Box<Expr>" 로 변환
                let parts: Vec<&str> = field.split_whitespace().collect();
                if parts.len() >= 2 {
                    let field_name = parts.last().unwrap();
                    let field_type = parts[..parts.len()-1].join(" ");
                    writeln!(file, "    pub {}: {},", field_name, field_type)?;
                }
            }
        }
    }

    writeln!(file, "}}\n")?;
    Ok(())
}
